from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.login),
    url(r'^cadastro/$', views.cadastro),
    url(r'^admin/$', views.admin),
    url(r'^admin/financeirovendas/$', views.financeiro),
    url(r'^admin/financeiropedidos/$', views.financeiroPedido),
    url(r'^admin/config/$', views.config),
    url(r'^admin/venda/$', views.ProssVenda),
    url(r'^admin/pedido/$', views.ProssPedido),
    url(r'^admin/cancelarvenda/(?P<id>\d+)', views.CancelaVenda),
    url(r'^admin/cancelarpedido/(?P<id>\d+)', views.CancelaPedido),
    url(r'^admin/excluirfinanceirovendas/(?P<pk>\d+)', views.ClearFinanceiro),
    url(r'^admin/excluirfinanceiropedido/(?P<pk>\d+)', views.ClearFinanceiroPedido),
    url(r'^admin/listarproduto/$', views.ListProduto),
    url(r'^admin/adicionarcliente/$', views.addcliente),
    url(r'^admin/adicionarfornecedor/$', views.addFornecedor),
    url(r'^admin/adicionarproduto/$', views.AddProduto),
    url(r'^admin/adicionarprodutofornecedor/(?P<id>\d+)', views.AddProdutoFornecedor),
    url(r'^admin/listarcliente/$', views.listCliente),
    url(r'^admin/listarvenda/$', views.listVenda),
    url(r'^admin/listarpedidos/$', views.listPedido),
    url(r'^admin/listarfornecedor/$', views.listFornecedor),
    url(r'^admin/excluircliente/(?P<pk>\d+)', views.excluirCliente),
    url(r'^admin/excluirfornecedor/(?P<pk>\d+)', views.excluirFornecedor),
    url(r'^admin/excluirproduto/(?P<pk>\d+)', views.excluirProduto),
    url(r'^admin/editarcliente/(?P<id>\d+)', views.editCliente),
    url(r'^admin/editarfornecedor/(?P<id>\d+)', views.editFornecedor),
    url(r'^admin/editarproduto/(?P<id>\d+)', views.editProduto),
    url(r'^admin/detalhecliente/(?P<id>\d+)', views.viewCliente),
    url(r'^admin/detalhefornecedor/(?P<id>\d+)', views.viewFornecedor),
    url(r'^admin/detalheproduto/(?P<id>\d+)', views.viewProduto),
    url(r'^admin/inseriremail/(?P<id>\d+)', views.AddEmail),
    url(r'^admin/inseriremailfornecedor/(?P<id>\d+)', views.AddEmailFornecedor),
    url(r'^admin/inseriruni/(?P<id>\d+)', views.AddUni),
    url(r'^admin/inserirendereco/(?P<id>\d+)', views.AddEnde),
    url(r'^admin/inserirenderecofornecedor/(?P<id>\d+)', views.AddEndeFornecedor),
    url(r'^admin/inserirdocumento/(?P<id>\d+)', views.AddDoc),
    url(r'^admin/inserirdocumentofornecedor/(?P<id>\d+)', views.AddDocFornecedor),
    url(r'^admin/excluiremail/(?P<idemail>\d+)', views.ClearEmail),
    url(r'^admin/excluiremailfornecedor/(?P<idemail>\d+)', views.ClearEmailFornecedor),
    url(r'^admin/excluirunidade/(?P<id>\d+)', views.ClearUni),
    url(r'^admin/excluirendereco/(?P<idende>\d+)', views.ClearEnde),
    url(r'^admin/excluirenderecofornecedor/(?P<idende>\d+)', views.ClearEndeFornecedor),
    url(r'^admin/excluirdocumento/(?P<iddoc>\d+)', views.ClearDoc),
    url(r'^admin/excluirdocumentofornecedor/(?P<iddoc>\d+)', views.ClearDocFornecedor),
    url(r'^sair/$', views.sair)
]