# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('foto', models.ImageField(blank=True, default='user/sem.png', upload_to='user/', verbose_name='Foto do cliente')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('foto', models.ImageField(blank=True, default='cliente/sem.png', upload_to='cliente/', verbose_name='Foto do cliente')),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntidade_parcelas', models.IntegerField(blank=True, default=5, verbose_name='Quantidade de Parcelas')),
                ('taxa_juro', models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, verbose_name='Taxa de Juro ao mes')),
                ('por_avista', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5, verbose_name='Porcentagem de Desconto a vista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do docuemento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do documento')),
                ('emissao', models.DateField(verbose_name='Data de Emiss\xe3o')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do docuemento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do documento')),
                ('emissao', models.DateField(verbose_name='Data de Emiss\xe3o')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descri\xe7\xe3o do email')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmailFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descri\xe7\xe3o do email')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=30, verbose_name='Cep')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do endere\xe7o')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o do endere\xe7o')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do endere\xe7o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=30, verbose_name='Cep')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do endere\xe7o')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o do endere\xe7o')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do endere\xe7o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Valor da parcela')),
                ('valor_total', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20, verbose_name='Status do financeiro')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceiroPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('valor_total', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor Total')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do fornecedor')),
                ('foto', models.ImageField(blank=True, default='fornecedor/sem.png', upload_to='fornecedor/', verbose_name='Foto do cliente')),
                ('ativo', models.BooleanField(default=True, verbose_name='esta ativo?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor')),
                ('item', models.ManyToManyField(to='loja.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=20, verbose_name='Produto')),
                ('foto', models.ImageField(blank=True, default='produto/sem.png', upload_to='produto/', verbose_name='Foto do cliente')),
                ('descricao_produto', models.CharField(blank=True, max_length=100, verbose_name='Descri\xe7\xe3o do produto')),
                ('estoque', models.IntegerField(verbose_name='Quantos no Estoque')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, verbose_name='Descri\xe7\xe3o da Unidade')),
                ('fator', models.IntegerField(verbose_name='Fator')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
                ('item', models.ManyToManyField(to='loja.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto'),
        ),
        migrations.AddField(
            model_name='financeiropedido',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor'),
        ),
        migrations.AddField(
            model_name='financeiropedido',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enderecofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor'),
        ),
        migrations.AddField(
            model_name='emailfornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor'),
        ),
        migrations.AddField(
            model_name='documentofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Fornecedor'),
        ),
    ]
