# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('foto', models.FileField(blank=True, upload_to='/cliente/', verbose_name='Foto do cliente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do docuemento')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do documento')),
                ('emissao', models.DateField(verbose_name='Data de Emiss\xe3o')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descri\xe7\xe3o do email')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=30, verbose_name='Cep')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do endere\xe7o')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descri\xe7\xe3o do endere\xe7o')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero do endere\xe7o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente')),
            ],
        ),
    ]
